# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ffbf223b6e042e419625e3739c4461b5c9714b575be2be6c6f8afa7c3c77ac5fecad4e5e395e56b0aa6795dd4c80b34a16c347a8ff730d83073f28eb1094191
  stripe_secret_key: sk_test_4tBxCu8cI5b3PJ5p2dfgwDgT
  stripe_publishable_key: pk_test_LqhCqKSqvFMK5V7OoR2GECv1
  recaptcha_secret_key: 6Le8AiQTAAAAAAErpzNUirxb7P8qdkP3WfqGPRMW
# host must be lowercase for captcha pass
  host: localhost
  server_admin: no-reply@quotr.ca


test:
  secret_key_base: 6c514940416a07420d3b8d8d5ed23c16e26e0f39e1647bdb66a8ed1224f7aaf4f86638c4cd144543073f6b3e5ec35d04ee9f06472e87b63dd08903821db54bff
  stripe_secret_key: sk_test_4tBxCu8cI5b3PJ5p2dfgwDgT
  stripe_publishable_key: pk_test_LqhCqKSqvFMK5V7OoR2GECv1
  recaptcha_secret_key: 6Le8AiQTAAAAAAErpzNUirxb7P8qdkP3WfqGPRMW
# host must be lowercase for captcha pass
  host: localhost
  server_admin: no-reply@quotr.ca


# Production keys are stored in a secure location and this file is swapped in post-deployment